# Generated by Django 5.0.1 on 2026-02-05 10:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("office_meeting", "Office Meeting (1 Day)"),
                            ("workshop_seminar", "Workshop/Seminar Follow Up (1 Day)"),
                            ("enquiry_followup", "Enquiry Follow Up (1 Day)"),
                            ("batch_commencement", "Batch Commencement Follow Up (1 Day)"),
                            ("fee_followup", "Fee Follow-up (1 Day)"),
                            ("urgent_task", "Urgent Task (12 hrs)"),
                            ("house_visit", "House Visit (2 Days)"),
                            ("lab_problem", "Lab Problem (1 Day)"),
                            ("request_suggestion", "Request / Suggestion (1 Day)"),
                            ("normal_task", "Normal Task (2 Days)"),
                            ("student_info", "Student Information (1 Day)"),
                            ("student_request", "Student Request (1 Day)"),
                            ("student_feedback", "Student Feedback (1 Day)"),
                            ("student_suggestion", "Student Suggestion (1 Day)"),
                            ("student_complaint", "Student Complaint (1 Day)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "activity_description",
                    models.TextField(
                        help_text="Maximum 255 characters", max_length=255
                    ),
                ),
                ("activity_date", models.DateField()),
                (
                    "start_time_hour",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "start_time_minute",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "duration_hour",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "duration_minute",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "person_to_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_1",
                    models.CharField(
                        blank=True,
                        help_text="Phone number with digits only",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "phone_2",
                    models.CharField(
                        blank=True,
                        help_text="Optional second phone number",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "venue",
                    models.TextField(
                        blank=True,
                        help_text="Maximum 255 characters",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Maximum 255 characters",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Maximum 255 characters",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="activities_created_765ec9_idx"
                    ),
                    models.Index(
                        fields=["activity_date"], name="activities_activit_7d1ab1_idx"
                    ),
                    models.Index(
                        fields=["executive"], name="activities_executi_7981b4_idx"
                    ),
                ],
            },
        ),
    ]
