# Generated by Django 6.0.2 on 2026-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('center', models.CharField(choices=[('all', 'All Centers'), ('TC016371', 'Electronic City PMKK Futureskill (TC016371)'), ('123', 'Rajajinagar (123)'), ('RAJBAN', 'Rajajinagar Bangalore (RAJBAN)'), ('RON', 'Rooman Online (RON)')], max_length=50)),
                ('enquiry_type', models.CharField(choices=[('corporate', 'Corporate'), ('email', 'EMAIL'), ('facebook', 'Facebook'), ('job_mela', 'JOB MELA'), ('old_student', 'Old Student'), ('online_registration', 'Online Registration'), ('placements', 'Placements'), ('referral_app', 'Referral APP'), ('seminar_workshop', 'Seminar/Workshop'), ('sms', 'SMS'), ('telephonic', 'TELEPHONIC'), ('walkin_others', 'WALK-IN (Others)'), ('walkin_experienced', 'Walk-in Experienced'), ('walkin_fresher', 'Walk-in Fresher')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('computer_knowledge', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('qualification', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('total_work_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
