# Generated by Django 6.0.2 on 2026-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('self_employed', 'Self Employed')], default='student', max_length=20, null=True),
        ),
    ]
