# Generated by Django 5.0.1 on 2026-02-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.CharField(blank=True, choices=[('advanced_java_005', 'Advanced Java (005)'), ('ai_in_cybersecurity_49', 'AI in Cybersecurity (49)'), ('application_developer_web_mobile_fsd', 'Application Developer Web and Mobile (FSD)'), ('aws_012', 'AWS (012)'), ('aws_internship', 'AWS Internship (Internship-1)'), ('aws_level_2', 'AWS Level 2 (AWS Advanced)'), ('ccna_009', 'CCNA (009)'), ('ccnp_23', 'CCNP (23)'), ('ccnp_enarsi', 'CCNP-ENARSI (CCNP 23.1)'), ('ccnp_encor', 'CCNP-ENCOR (CCNP 23)'), ('core_java_004', 'Core Java (004)'), ('core_java_pap', 'Core Java (PAP) (PAP-1)'), ('cyber_security_10', 'Cyber Security (10)'), ('data_analytics_internship', 'Data Analytics Internship (Internship-2)'), ('data_science_ai_28', 'Data Science & AI (28)'), ('data_science_business_analytics_001', 'Data Science & Business Analytics (001)'), ('data_science_machine_learning_019', 'Data Science & Machine Learning (019)'), ('ethical_hacking_011', 'Ethical Hacking (011)'), ('front_end_technologies_006', 'Front End Technologies (006)'), ('full_stack_cloud_devops', 'Full Stack Cloud & DevOps (FutureAcad-04)'), ('full_stack_cyber_security', 'Full Stack Cyber Security (FutureAcad-03)'), ('full_stack_development_python_26', 'Full Stack Development – Python (26)'), ('full_stack_software_developer_internship', 'Full Stack Software Developer Internship (Internship-3)'), ('full_stack_software_developer_genai', 'Full Stack Software Developer with GenAI (FutureAcad-06)'), ('hardware_and_networking_37', 'Hardware and Networking (37)'), ('interview_prep_program', 'Interview Prep Program (Interview-1)'), ('java_frameworks_27', 'Java Frameworks (27)'), ('machine_learning_002', 'Machine Learning (002)'), ('master_data_analytics_ml', 'Master in Data Analytics & Machine Learning (FutureAcad-02)'), ('master_nextgen_ai_data_science', 'Master in NextGen AI & Data Science (FutureAcad-01)'), ('mysql_nosql_014', 'MySQL / NoSQL (014)'), ('networking_cyber_security_22', 'Networking & Cyber Security (22)'), ('networking_essentials', 'Networking Essentials (Net-Ess)'), ('professional_cloud_devops', 'Professional in Cloud and DevOps (Professional-08)'), ('professional_core_it_ops', 'Professional in Core IT Ops: Network, Server & Cloud (Professional-01)'), ('professional_cyber_security_expert', 'Professional in Cyber Security Expert (Professional-06)'), ('professional_data_analytics', 'Professional in Data Analytics (Professional-03)'), ('professional_generative_ai_mlops', 'Professional in Generative AI and MLOps (Professional-05)'), ('professional_ml_deep_learning', 'Professional in Machine Learning & Deep Learning (Professional-04)'), ('professional_web_development_dsa', 'Professional in Web Development & DSA (Professional-02)'), ('python_frameworks_008', 'Python Frameworks (008)'), ('python_programming_007', 'Python Programming (007)'), ('server_admin_cloud_computing_21', 'Server Admin & Cloud Computing (21)'), ('soft_skills_43', 'Soft Skills (43)'), ('vmware_essentials_13', 'VMWare Essentials (13)'), ('windows_server_administrator_24', 'Windows Server Administrator (24)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='reason_for_enquiry',
            field=models.CharField(blank=True, choices=[('for_knowledge', 'For knowledge'), ('internship_or_project', 'Internship or project'), ('upskilling', 'Upskilling'), ('placements', 'Placements')], max_length=50, null=True),
        ),
    ]
