# Generated by Django 6.0.2 on 2026-02-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_activity'),
        ('custom_admin', '0003_alter_enquiry_status'),
    ]

    operations = [
    ]
