# Generated by Django 5.0.1 on 2026-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_enquiry_course_enquiry_reason_for_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='stage',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('LEAD', 'Lead'), ('CONVERTED', 'Converted')], default='ENQUIRY', max_length=20),
        ),
    ]
