# Generated by Django 6.0.2 on 2026-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_merge_0002_activity_0003_alter_enquiry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, unique=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Course Fee Structure',
                'verbose_name_plural': 'Course Fee Structures',
                'db_table': 'course_fee_structure',
                'ordering': ['course_name'],
            },
        ),
    ]
