# Generated by Django 5.0.1 on 2026-02-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_enquiry_lead_status_enquiry_notes_enquiry_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('no_response', 'No Response'), ('call_back', 'Call Back')], max_length=20)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='custom_admin.enquiry')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'db_table': 'follow_ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
