# Generated by Django 6.0.2 on 2026-02-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_studentinvoice_invoiceinstallment_studentreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinvoice',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentreceipt',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='studentreceipt',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='InvoiceInstallment',
        ),
        migrations.DeleteModel(
            name='StudentInvoice',
        ),
        migrations.DeleteModel(
            name='StudentReceipt',
        ),
    ]
