# Generated by Django 6.0.2 on 2026-02-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_studentinvoice_invoiceinstallment_studentreceipt'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Salary Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_status', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Salary Status',
                'verbose_name_plural': 'Employee Salary Statuses',
                'db_table': 'employee_salary_status',
            },
        ),
    ]
