# Generated by Django 5.0.1 on 2026-02-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_followup'),
        ('custom_admin', '0009_studentinvoice_invoiceinstallment_studentreceipt'),
    ]

    operations = [
    ]
