# Generated by Django 5.0.1 on 2026-02-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0011_batch_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='center',
            field=models.CharField(blank=True, choices=[('Electronic City PMKK Futureskill (TC016371)', 'Electronic City PMKK Futureskill (TC016371)'), ('Rajajinagar (123)', 'Rajajinagar (123)'), ('Rajajinagar Bangalore (RAJBAN)', 'Rajajinagar Bangalore (RAJBAN)'), ('Rooman Online (RON)', 'Rooman Online (RON)')], max_length=100, null=True),
        ),
    ]
