# Generated by Django 5.0.1 on 2026-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0012_batch_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='classroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
