# Generated by Django 6.0.2 on 2026-02-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='center',
            field=models.CharField(blank=True, choices=[('Electronic City PMKK Futureskill (TC016371)', 'Electronic City PMKK Futureskill (TC016371)'), ('Rajajinagar (123)', 'Rajajinagar (123)'), ('Rajajinagar Bangalore (RAJBAN)', 'Rajajinagar Bangalore (RAJBAN)'), ('Rooman Online (RON)', 'Rooman Online (RON)')], max_length=100, null=True),
        ),
    ]
