# Generated by Django 5.0.1 on 2026-02-11 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0014_session_conducted_date_session_conducted_end_time_and_more'),
        ('student', '0002_add_center_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='custom_admin.batch'),
        ),
    ]
